name: Daily Job Scraper

on:
  schedule:
    - cron: '0 10 * * *'  # Daily at 12 PM CET
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies (Selenium + Chrome)
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        pip install selenium requests beautifulsoup4 chromedriver-autoinstaller

    - name: Install Chromium and matching ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        pip install selenium requests beautifulsoup4

    - name: Install Google Chrome and chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
        DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
        wget -O chromedriver.zip "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver
        pip install selenium requests beautifulsoup4


    - name: Run job scraper script (Selenium)
      env:
        BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: python final_job_scraper.py
