name: Daily Job Scraper

on:
  schedule:
    - cron: '0 10 * * *'  # Daily at 12 PM CET
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies (Selenium + Chrome)
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        pip install selenium requests beautifulsoup4

    - name: Set CHROME environment
      run: echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV

    - name: Run job scraper script (Selenium)
      env:
        BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: python final_job_scraper.py
